app1/urls.py
from django.urls import path
from .views import about,elements,contact,index,newsletter

app_name='app1'

urlpatterns = [
    path('',index,name='index'),
    path('about',about,name='about'),
    path('elements',elements,name='elements'),
    path('contact',contact,name='contact'),
    path('newsletter',newsletter,name='newsletter'),

]

blog/urls.py
from django.urls import path
from .views import blog_home,blog_single,blog_search

app_name='blog'

urlpatterns = [
    path('',blog_home,name='index'),
    path('<int:pid>',blog_single,name='single'),
    path('category/<str:cat_name>',blog_home,name='category'),
    path('tag/<str:tag_name>',blog_home,name='tag'),
    # path('author/<str:author_username>',blog_home,name='author'),
    path('search/',blog_search,name='search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
# from .views import home
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from app1.sitemaps import StaticViewSitemap
from blog.sitemaps import Blogsitemap

sitemaps = {'static':StaticViewSitemap,
            'blog':Blogsitemap
            }

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',home),
    # path('app1/',include('app1.urls')),
    path('',include('app1.urls')),
    path('blog/',include('blog.urls')),
    # path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt',include('robots.urls')),
    path('summernote/',include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Post(models.Model):
    #tag #category #author #image
    category=models.ManyToManyField(Category)
    image=models.ImageField(upload_to='blog/',default='blog/default.jpg')
    author=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    tags=TaggableManager()
    title = models.CharField(max_length=255)
    content = models.TextField()
    counted_views=models.IntegerField(default=0)
    status=models.BooleanField(default=False)
    published_date=models.DateTimeField(null=True)
    created_date=models.DateTimeField(auto_now_add = True)
    updated_date=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('blog:single',kwargs={'pid':self.id})

class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    name=models.CharField(max_length=255)
    email=models.EmailField()
    subject=models.CharField(max_length=255)
    message = models.TextField()
    approved=models.BooleanField(default=False)
    created_date=models.DateTimeField(auto_now_add = True)
    updated_date=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from blog.models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['name','email','subject','message']

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post,Comment
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from blog.forms import CommentForm
from django.contrib import messages
from django.utils import timezone
# import datetime


def blog_home(request,cat_name=None,tag_name=None):
    posts=Post.objects.filter(status=1)
    # posts=posts.filter(published_date__lte=timezone.now())
    if cat_name:
        posts=posts.filter(category__name=cat_name)
    '''
    if author_username:
        posts=posts.filter(author__username=author_username)
    attach: ,author_username=None  to:blog_home(here)
    '''
    if tag_name:
        posts=posts.filter(tags__name__in=tag_name)

    posts=Paginator(posts,3)
    try:
        page_number=request.GET.get('page')
        posts=posts.get_page(page_number)
    except PageNotAnInteger:
        posts=posts.get_page(1)
    except EmptyPage:
        posts=posts.get_page(1)

    context={'posts':posts}
    return render(request,'blog/blog-home.html',context)



'''
        #3
        p=Post.objects.filter(published_date__lt=post.published_date).order_by('-published_date')
        n=Post.objects.filter(published_date__gt=post.published_date).order_by('published_date')

        for i in n:
            print(i.status)
            if i.status == True:
                next_post = Post.objects.filter(id=i.id,published_date__gt=post.published_date).order_by('published_date')
                break
        for j in p:
            print(j.status)
            if j.status == True:
                previous_post = Post.objects.filter(id=j.id,published_date__lt=post.published_date).order_by('published_date')
                break

        postt = get_object_or_404(Post,id__lt=pid,id__gt=pid-2,status=1)
        print(postt)
'''
        #1
        # if Post.objects.filter(id=pid+1,status=1).exists():

        #2
        # post=get_object_or_404(Post,id=pid,status=1)
        # post=post.filter(published_date__lte==post.published_date)

        # print(next_post.values_list('content', flat=True))
        # next_post = posts.get_next_by_published_date()
        # print(next_post)
        # print(previous_post)

def blog_single(request,pid):
    if request.method =='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SECCESS,'aqa shod')
        else:
            messages.add_message(request,messages.ERROR,'aqa nashod')
    else:
        posts=get_object_or_404(Post,id=pid,status=1)
        posts.counted_views+=1
        posts.save()

        post=get_object_or_404(Post,id=pid,status=1)
        comments=Comment.objects.filter(post=post.id,approved=True).order_by('-created_date')

        nextPost = Post.objects.filter(published_date__gt=post.published_date).order_by('published_date').first()
        prevPost = Post.objects.filter(published_date__lt=post.published_date).order_by('published_date').last()

        context={'posts':posts,'comments':comments,'nextpost': nextPost, 'prevpost': prevPost}
        return render(request,'blog/blog-single.html',context)


def blog_search(request):
    posts=Post.objects.filter(status=1)
    if request.method=='GET':
        posts=posts.filter(content__contains=request.GET.get('s'))
    context={'posts':posts}
    return render(request,'blog/blog-home.html',context)

templates/blog/blog-ads.html
{%load static%}

<div class="single-sidebar-widget ads-widget">
  <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
</div>

templates/blog/blog-category.html
{%load static%}

<div class="single-sidebar-widget post-category-widget">
  <h4 class="category-title">Post Catgories</h4>
  <ul class="cat-list">
    {%for name,count in categories.items%}
    <li>
      <a href="{%url 'blog:category' cat_name=name %}" class="d-flex justify-content-between">
        <p>{{name}}</p>
        <p>{{count}}</p>
      </a>
    </li>
    {%endfor%}
  </ul>
</div>

templates/blog/blog-home.html
{% extends 'base.html'%}
{%load static%}
{%block content%}
{%load blog-tags%}

			<!-- End banner Area -->

			<!-- Start top-category-widget Area -->
			<section class="top-category-widget-area pt-90 pb-90 ">
				<div class="container">
					<div class="row">
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget1.jpg' %}" alt="">

								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Social life</h4>
								        <span></span>
								        <p>Enjoy your social life together</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget2.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Politics</h4>
								        <span></span>
								        <p>Be a part of politics</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget3.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Food</h4>
								        <span></span>
								        <p>Let the food be finished</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!-- End top-category-widget Area -->

			<!-- Start post-content Area -->
			<section class="post-content-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">


							{% for post in posts %}
							<div class="single-post row">
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">

									{% for cat in post.category.all%}
									<a href="{%url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a>
									{%if not forloop.last%}
									,
									{%endif%}
									{% endfor %}

									</ul>
									

									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{post.author.get_full_name}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|date:"d M Y" }}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_views}} Views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span></p>
									</div>
								</div>
								<div class="col-lg-9 col-md-9 ">
									<div class="feature-img">
										<img class="img-fluid" src="{{post.image.url}}" alt="">
									</div>
									<a class="posts-title" href="{%url 'blog:single' pid=post.id %}"><h3>{{post.title}}</h3></a>
									<p class="excert">
										<!-- {{post.content|truncatechars:50}} -->
										{{ post.content|truncatewords_html:2 }}
									</p>
									<a href="{%url 'blog:single' pid=post.id %}" class="primary-btn">View More</a>
								</div>
							</div>
							{%endfor%}

		                    <nav class="blog-pagination justify-content-center d-flex">
		                        <ul class="pagination">
															{%if posts.has_previous%}
		                            <li class="page-item">
		                                <a href="?page={{posts.previous_page_number}}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
																{%endif%}

																{%for i in posts.paginator.page_range%}
																{%if posts.number == i%}
																	<li class="page-item active" ><a href="?page={{i}}" class="page-link">{{i}}</a></li>
																	{%else%}
																	<li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
																	{%endif%}
																{%endfor%}

																{%if posts.has_next%}
		                            <li class="page-item">
		                                <a href="?page={{posts.next_page_number}}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
																{%endif%}
		                        </ul>
		                    </nav>
										</div>

						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">


						{%include 'blog/blog-search.html'%}
						{%include 'blog/blog-writer.html'%}
						{%latestpost%}
						{%include 'blog/blog-ads.html'%}
						{%postcategories%}
						{%include 'blog/blog-newsletter.html'%}
						{%include 'blog/blog-tagclouds.html'%}

							</div>

						</div>

					</div>
				</div>
			</section>
			<!-- End post-content Area -->

{%endblock%}

templates/blog/blog-latestpost.html
{%load static%}


<div class="single-sidebar-widget popular-post-widget">
      <h4 class="popular-title">Popular Posts</h4>
      <div class="popular-post-list">

{%for post in postt%}
          <div class="single-post-list d-flex flex-row align-items-center">
              <div class="thumb">
                  <img class="img-fluid" src="{{post.image.url}}" alt="">
              </div>
              <div class="details">
                  <a href="{%url 'blog:single' pid=post.id %}"><h6>{{post.title}}</h6></a>
                  <p>02 Hours ago</p>
              </div>
          </div>
{%endfor%}


      </div>
  </div>

templates/blog/blog-newsletter.html
{%load static%}
<div class="single-sidebar-widget newsletter-widget">
  <h4 class="newsletter-title">Newsletter</h4>
  <p>
    Here, I focus on a range of items and features that we use in life without
    giving them a second thought.
  </p>
  <div class="form-group d-flex flex-row">
     <div class="col-autos">
        <div class="input-group">
          <div class="input-group-prepend">
            <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
      </div>
          </div>
          <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" >
        </div>
      </div>
      <a href="#" class="bbtns">Subcribe</a>
  </div>
  <p class="text-bottom">
    You can unsubscribe at any time
  </p>
</div>

templates/blog/blog-search.html
{%load static%}

<div class="single-sidebar-widget search-widget">
  <form class="search-form" action="{%url 'blog:search'%}" method:"get">
    <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
    <button type="submit"><i class="fa fa-search"></i></button>
</form>
</div>

templates/blog/blog-single.html
{% extends 'base.html'%}
{%load static%}
{%block content%}
{%load blog-tags%}

			<!-- start banner Area -->
			<section class="relative about-banner">
				<div class="overlay overlay-bg"></div>
				<div class="container">
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								{{posts.title}}
							</h1>
							<p class="text-white link-nav"><a href="{%url 'app1:index' %}">Home </a>  <span class="lnr lnr-arrow-right"></span><a href="{%url 'blog:index'%}">Blog </a> <span class="lnr lnr-arrow-right"></span> <a href="{%url 'blog:single' pid=posts.id %}"> {{posts.title}}</a></p>
						</div>
					</div>
				</div>
			</section>
			<!-- End banner Area -->

			<!-- Start post-content Area -->
			<section class="post-content-area single-post-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
							<div class="single-post row">
								<div class="col-lg-12">
									<div class="feature-img">
										<img class="img-fluid" src="{{posts.image.url}}" alt="">
									</div>
								</div>
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">

										{% for cat in posts.category.all%}
										<a href="{%url 'blog:category' cat_name=cat.name%}">{{cat.name}}</a>
										{%if not forloop.last%}
										,
										{%endif%}
										{% endfor %}
									</ul>
									<div class="user-details row">
	
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{posts.author.get_full_name}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{posts.published_date|date:"d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{posts.counted_views}} Views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span></p>
										<ul class="social-links col-lg-12 col-md-12 col-6">
											<li><a href="#"><i class="fa fa-facebook"></i></a></li>
											<li><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-github"></i></a></li>
											<li><a href="#"><i class="fa fa-behance"></i></a></li>
										</ul>
									</div>
								</div>
								<div class="col-lg-9 col-md-9">
									<h3 class="mt-20 mb-20">{{posts.title}}</h3>
									<p class="excert">
										{{posts.content|safe}}
									</p>
								</div>
							</div>



						<div class="navigation-area">
									<div class="row">



										<div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">



										{% if prevpost %}
										<div class="thumb">
											<a href="{{prevpost.id}}"><img class="img-fluid" src="{{prevpost.image.url}}" alt=""></a>
										</div>
										<div class="arrow">
											<a href="{{prevpost.id}}"><span class="lnr text-white lnr-arrow-left"></span></a>
										</div>
										<div class="detials">
											<p>Prev Post</p>
											<a href="{{prevpost.id}}"><h4>{{prevpost.title}}</h4></a>
										</div>


										{% else %}
										<div class="thumb">
										<a href="{% url 'blog:index' %}"><img class="img-fluid"	src="{% static 'img/travelista.png' %}" alt=""></a>
										</div>
										<div class="arrow">
										<a href="{% url 'blog:index' %}"><span class="lnr text-white lnr-arrow-left"></span></a>
										</div>
										<div class="detials">
										<p>Home</p>
										<a href="{% url 'blog:index' %}"><h4>blog</h4></a>
										</div>
										{% endif %}



										</div>



										<div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">




											{% if nextpost %}
											<div class="detials">
												<p>Next Post</p>
												<a href="{{nextpost.id}}"><h4>{{nextpost.title}}</h4></a>
											</div>
											<div class="arrow">
												<a href="{{nextpost.id}}"><span class="lnr text-white lnr-arrow-right"></span></a>
											</div>
											<div class="thumb">
												<a href="{{nextpost.id}}"><img class="img-fluid" src="{{nextpost.image.url}}" alt=""></a>
											</div>

											{% else %}
												<div class="thumb">
												<a href="{% url 'blog:index' %}"><img class="img-fluid"	src="{% static 'img/travelista.png' %}" alt=""></a>
												</div>
												<div class="arrow">
												<a href="{% url 'blog:index' %}"><span class="lnr text-white lnr-arrow-right"></span></a>
												</div>
												<div class="detials">
												<p>Home</p>
												<a href="{% url 'blog:index' %}"><h4>blog</h4></a>
												</div>
												{% endif %}



										</div>






									</div>
								</div>
















							<div class="comments-area">
								<h4>{{comments|length}} Comments</h4>
								{%for comment in comments%}
								<div class="comment-list">
                                    <div class="single-comment justify-content-between d-flex">
                                        <div class="user justify-content-between d-flex">
                                            <div class="thumb">
                                                <img src="{% static 'img/blog/c1.jpg' %}" alt="">
                                            </div>
                                            <div class="desc">
                                                <h5><a href="#">{{comment.name}}</a></h5>
                                                <p class="date">{{comment.created_date}}</p>
                                                <p class="comment">
                                                  {{comment.message}}
                                                </p>
                                            </div>
                                        </div>
                                        <div class="reply-btn">
                                               <a href="" class="btn-reply text-uppercase">reply</a>
                                        </div>
                                    </div>
                </div>
								{%endfor%}
							</div>


							<div class="comment-form">
								<h4>Leave a Comment</h4>
								<form method="post" action="{%url "blog:single" pid=posts.id%}">
									{%csrf_token%}
									<div class="form-group form-inline">
									  <div class="form-group col-lg-6 col-md-12 name">
									    <input type="text" class="form-control" name="name" placeholder="Enter Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
									  </div>
									  <div class="form-group col-lg-6 col-md-12 email">
									    <input type="email" class="form-control" name="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
									  </div>
									</div>
									<div class="form-group">
										<input type="text" class="form-control" name="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
									</div>
									<div class="form-group">
										<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
									</div>
									<input type="hidden" name="post" value="{{posts.id}}">
									<button type='submit' class="primary-btn text-uppercase">Post Comment</button>
								</form>

							</div>

<!--
comment gozari ba disqus

<div class="comments-area">
							<div id="disqus_thread"></div>
							<script>
					    (function() { // DON'T EDIT BELOW THIS LINE
					    var d = document, s = d.createElement('script');
					    s.src = 'https://127-0-0-1-8000-eeemztveee.disqus.com/embed.js';
					    s.setAttribute('data-timestamp', +new Date());
					    (d.head || d.body).appendChild(s);
					    })();
							</script>
							<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
	</div>
-->









						</div>

						<div class="col-lg-4 sidebar-widgets">

							<div class="widget-wrap">

								{%include 'blog/blog-search.html'%}
								{%include 'blog/blog-writer.html'%}
								{%latestpost%}
								{%include 'blog/blog-ads.html'%}
								{%postcategories%}
								{%include 'blog/blog-newsletter.html'%}
								{%include 'blog/blog-tagclouds.html'%}

							</div>

						</div>

					</div>
				</div>
			</section>
			<!-- End post-content Area -->

{%endblock%}

templates/blog/blog-tagclouds.html
{%load static%}

<div class="single-sidebar-widget tag-cloud-widget">
  <h4 class="tagcloud-title">Tag Clouds</h4>
  <ul>
    {% for tag in post.tags.all %}
    <li><a href="{%url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></li>
    {%endfor%}
  </ul>
</div>

templates/blog/blog-writer.html
{%load static%}

<div class="single-sidebar-widget user-info-widget">
  <img src="{% static 'img/blog/user-info.png' %}" alt="">

  <a href="#"><h4>Charlie Barber</h4></a>
  <p>
    Senior blog writer
  </p>
  <ul class="social-links">
    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
    <li><a href="#"><i class="fa fa-github"></i></a></li>
    <li><a href="#"><i class="fa fa-behance"></i></a></li>
  </ul>
  <p>
    Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.
  </p>
</div>